# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-05 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_auto_20170305_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='username',
            field=models.CharField(default='user', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Cartype'),
        ),
        migrations.AlterField(
            model_name='order',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Client'),
        ),
    ]
